// These styles apply to every route in the application
import './globals.css'
import Navbar from 'components/navbar'
import MainBorder from 'components/mainborder'
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
 
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Navbar/>
      <body>
	<MainBorder>
	{children}
	</MainBorder>
      </body>
    </html>
  )
}
